-- ==================== REVIEWS TABLE ====================
-- This table was required by 20260215120000_trust_and_growth.sql
-- but was missing from the migration history.

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  listing_id bigint not null references public.listings(id) on delete cascade,
  seller_id uuid not null references public.profiles(id) on delete cascade,
  buyer_id uuid not null references public.profiles(id) on delete cascade,
  buyer_name text not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamptz not null default now(),
  constraint reviews_order_unique unique (order_id)
);

-- Enable RLS
alter table public.reviews enable row level security;

-- Policies
create policy "Reviews are viewable by everyone"
  on public.reviews for select
  using (true);

create policy "Buyers can insert reviews for their orders"
  on public.reviews for insert
  with check (auth.uid() = buyer_id);

create policy "Buyers can update their own reviews"
  on public.reviews for update
  using (auth.uid() = buyer_id);

-- Indexes
create index if not exists idx_reviews_seller on public.reviews(seller_id);
create index if not exists idx_reviews_buyer on public.reviews(buyer_id);
create index if not exists idx_reviews_listing on public.reviews(listing_id);
